#!/bin/bash

git clone https://github.com/dahekars/Ai_snake.git
git clone https://github.com/dahekars/Angel_bot.git
git clone https://github.com/dahekars/YTD-Youtubedownloader.git
git clone https://github.com/dahekars/snakegame.git
git clone https://github.com/dahekars/Tetris
#git clone https://github.com/EpicGames/UnrealEngine.git --branch=4.22
