#!/bin/bash

mkdir ~/PersonalProjects/code

git clone https://github.com/dahekars/Ai_snake.git ~/PersonalProjects/code/
git clone https://github.com/dahekars/Angel_bot.git ~/PersonalProjects/code/
git clone https://github.com/dahekars/YTD-Youtubedownloader.git ~/PersonalProjects/code/
git clone https://github.com/dahekars/snakegame.git ~/PersonalProjects/code/
git clone https://github.com/dahekars/Tetris ~/PersonalProjects/code/
#git clone https://github.com/EpicGames/UnrealEngine.git --branch=4.22 ~/PersonalProjects/code/
