#!/bin/bash
read -p "which package manager: " pkmg

function\(installtools\){
    # VScode
    sudo $pkmg install snapl
    sudo snap install --classic code # VScode 

    # Discord
    wget https://discord.com/api/download?platform=linux&format=deb -P /tmp/discord.deb #downlaod Discord from web
    sudo $pkmg install ./tmp/discord.deb #start installing discord

    #terminator
    sudo $pkmg install terminator

    # XDM
    mkdir /tmp/XDM
    wget https://github.com/subhra74/xdm/releases/download/7.2.11/xdm-setup-7.2.11.tar.xz -P /tmp/XDM/
    tar –xvzf /tmp/XDM/*
    #gnome-terminal -- ./tmp/XDM/

    #ssh
    sudo $pkmg install openssh-server

    #VMBox install
    sudo $pkmg install virtualbox

    # VLC
    sudo $pkmg install vlc

    #microsoft Teams
    sudo $pkmg install teams

    #GNS 3
    sudo pip3 install gns3-server
    sudo pip3 install gns3-gui
    sudo apt install python3-pyqt5.QtSvg python3-pyqt5.qtwebsockets dynamips

    #chrome install
    mkdir /tmp/chrome
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp/chrome/
    sudo $pkmg install ./tmp/chrome/google-chrome-stable_current_amd64.deb
}
