#!/bin/bash
read -p "which package manager: " pkmg

function\(installtools\){
    # VScode
    sudo $pkmg install snapl
    sudo snap install --classic code # VScode 

    # Discord
    wget https://discord.com/api/download?platform=linux&format=deb -P /tmp/discord.deb #downlaod Discord from web
    sudo $pkmg install ./tmp/discord.deb #start installing discord

    #terminator
    sudo $pkmg install terminator

    # XDM
    
}
